coverage:
  status:
    patch:
      default:
        informational: true
        target: auto
    project:
      default:
        informational: true
        target: auto

comment:
  layout: "newheader,reach,diff,files,newfooter,betaprofiling"
  show_critical_paths: true
