export default Color;
declare const Color: Readonly<{
    black: "black";
    red: "red";
    green: "green";
    yellow: "yellow";
    blue: "blue";
    magenta: "magenta";
    cyan: "cyan";
    white: "white";
    lightblack: "lightblack";
    lightred: "lightred";
    lightgreen: "lightgreen";
    lightyellow: "lightyellow";
    lightblue: "lightblue";
    lightmagenta: "lightmagenta";
    lightcyan: "lightcyan";
    lightwhite: "lightwhite";
    grey: "grey";
    lightgrey: "lightgrey";
}>;
